# Generated by Django 4.2.4 on 2023-08-10 12:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(default='SOME STRING', verbose_name='Текст'),
        ),
    ]
